# Generated by Django 5.2.4 on 2025-07-10 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialización')),
                ('numero_licencia', models.CharField(max_length=50, unique=True, verbose_name='Número de Licencia')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_prerfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('numero_cita', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número de Cita')),
                ('tipo_cita', models.CharField(choices=[('consulta', 'Consulta'), ('servicio', 'Servicio'), ('tratamiento', 'Tratamiento'), ('cirugia', 'Cirugía'), ('emergencia', 'Emergencia')], max_length=20, verbose_name='Tipo de Cita')),
                ('fecha_hora_cita', models.DateTimeField(verbose_name='Fecha y Hora de la Cita')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('estado', models.CharField(choices=[('active', 'Activa'), ('deleted', 'Eliminada'), ('completed', 'Completada'), ('cancelled', 'Cancelada')], default='active', max_length=20, verbose_name='Estado')),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación')),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_eliminadas', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
                ('paciente', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='pacientes.paciente', verbose_name='Paciente')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='citas.doctor', verbose_name='Doctor')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha_hora_cita'],
            },
        ),
    ]
