# Generated by Django 5.2.4 on 2025-07-10 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_doctor_usuario'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='usuarios.doctor', verbose_name='Doctor'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
